# Generated by Django 2.2.4 on 2019-09-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190918_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='home_delivery_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
