# Generated by Django 2.2.6 on 2019-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191118_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_id',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
