# Generated by Django 2.2.6 on 2019-11-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_add_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(null=True, upload_to='main_product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(null=True, upload_to='main_product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(null=True, upload_to='main_product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(null=True, upload_to='main_product'),
        ),
    ]
